services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: vault-db
    environment:
      - POSTGRES_USER=vault_user
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=vault_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data