spring:
  application:
    name: the-vault

  datasource:
    url: jdbc:postgresql://localhost:5432/vault_db
    username: vault_user
    password: secret_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      enabled: false

  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.web: DEBUG

application:
  security:
    # Syntax: ${ENV_VAR_NAME:default_value_only_for_dev}
    # Ideally, remove the default value in production.
    encryption-key: ${VAULT_ENCRYPTION_KEY}
